# use numpy

In [2]:
#first off all we will call numpy libraries and name it np to make it more simple (optional)
import numpy as np

In [6]:
# we make np array so we can use it for some numpy operation
x = np.array([4,5,5,6,6,4])

array([4, 5, 5, 6, 6, 4])

In [8]:
#see the different between numpy and normal array
type(x)

numpy.ndarray

In [20]:
y = [2,3,3,4,5,5,5]

In [21]:
type(y)

list

# Some function

changing data type

In [62]:
#we have our x data type integer
x = np.array([4,5,5,6,6,4])
x.dtype

dtype('int32')

In [63]:
#change x to float (have comma)
x = x.astype('f')

In [65]:
x

array([4., 5., 5., 6., 6., 4.], dtype=float32)

In [68]:
#change x to string
x = x.astype('S')

In [70]:
x

array([b'4.0', b'5.0', b'5.0', b'6.0', b'6.0', b'4.0'], dtype='|S32')

the datatype is here \\ sc: w3school
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

find array count

In [91]:
# x have 5 total element
x = np.array([2,3,2,3,4])
x.shape

(5,)

In [101]:
#lets make 2 dimensional array
x = np.array([[2,3,2,3,4],[1,1,1,1,4]])

In [103]:
x.shape
# 2,5 means we have 2 array with 5 element each

(2, 5)

change array dimension

In [161]:
# we have x the 2 dimensional array
x = np.array([[2,3,2,3,4],[1,1,1,1,4]])

In [132]:
# how to get 0 and 1 index
x[0]

array([2, 3, 2, 3, 4])

In [133]:
x[1]

array([1, 1, 1, 1, 4])

In [165]:
# we use -1 means it can be any number to fit the dimension (in this case it will be 1 dimension)
y = x.reshape(-1)

In [168]:
# now y is x 1 dimensional array
y

array([2, 3, 2, 3, 4, 1, 1, 1, 1, 4])

2 dimension

In [139]:
#we have y the 1 dimensional array with 10 element
y = np.array([2, 3, 2, 3, 4, 1, 1, 1, 1, 4])

In [178]:
#we can split them to 2 dimension 
a = y.reshape(2,5)
# 2,5 means 2  row and 5 column

In [181]:
a

array([[2, 3, 2, 3, 4],
       [1, 1, 1, 1, 4]])

In [179]:
# lets try using -1
b = y.reshape(-2,5)
# 2,5 means 2  row and 5 column

In [182]:
b

array([[2, 3, 2, 3, 4],
       [1, 1, 1, 1, 4]])